### ISSUE TITLE
Elixir in action (second edition) by Saša Jurić 

### ISSUE THREAD

**Issue by SimonLab** [dwyl/library#80]
https://www.manning.com/books/elixir-in-action-second-edition

Do we have this one already?

**Comment by nelsonic** [comment]
I didn't buy the _first_ edition of the book because we already had the "_official_" book:
![image](https://user-images.githubusercontent.com/194400/52630366-f7078680-2eb3-11e9-97e4-e4a22a71dd83.png)

> @SimonLab have you worked through all the _examples_ in **Programming Elixir 1.6**?

The reviews for the [_first_ edition](https://www.amazon.co.uk/Elixir-Action-Saša-Juri-cacute/dp/161729201X/ref=sr_1_1?ie=UTF8&qid=1549967887&sr=8-1&keywords=elixir+in+action#customerReviews) were not "_compelling_":
![image](https://user-images.githubusercontent.com/194400/52630541-654c4900-2eb4-11e9-862a-9029d078e3cb.png)


The _second_ edition was released/updated _recently_ ... (28 Jan 2019) but is "***out of stock***":

https://www.amazon.co.uk/Elixir-Action-Second-Sasa-Juric/dp/1617295027/
![image](https://user-images.githubusercontent.com/194400/52629851-8f9d0700-2eb2-11e9-8343-0b1254fec541.png)

The _Second_ edition only has **_one_ review** on Amazon.com:
![image](https://user-images.githubusercontent.com/194400/52630065-194cd480-2eb3-11e9-8664-7264281cc257.png)
When _anything_ on Amazon has _one_ review, my _immediate/only_ thought is: 
this review was left by a "sympathetic" person (_e.g: the Author's best friend_...)

But ... given that you (Simon) have taken the initiative to open this issue, 
I'm guessing that you have done the _research_ and concluded that it's worth your/our time to read it.

Bought it _direct_ from the publisher to ensure the author gets the _most_ cash for their work:
![image](https://user-images.githubusercontent.com/194400/52631094-c88aab00-2eb5-11e9-8e0e-4bfb669b521f.png)

I've updated the email address on the account to be the _shared_ one so that you have _direct_ access.

**Comment by SimonLab** [comment]
Thanks @nelsonic :tada: 
The reviews have read were saying to read half of Programming Elixir to learn the basic of the language then to move to Elixir in action to learn more specific/advance elixir concepts.
But I was curious to see how it compares to Programming in Elixir

**Comment by nelsonic** [comment]
@SimonLab cool. I look forward to reading it too.

**Comment by SimonLab** [comment]
got the :books: :
